apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: woocommerce-pvc
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 5Gi
    storageClassName: "scw-bssd"